### PR TITLE
Comment alignment

### PR DESCRIPTION
**Pull request by a8568730**
### Overview

Align all comments according to the max length of candidates.

|Before|After|
|--|--|
|截圖 2020-11-26 上午11 43 54|截圖 2020-11-26 上午11 22 54|

### CODE REVIEW

**Comment by LEOYoon-Tsaw** [comment]
Use a <tab> cannot guarantee alignment, whereas the space between candidate and comment becomes variable.
Besides, did you test fir linear mode? I doubt it will ruin linear mode.

**Comment by a8568730** [comment]
Weasel for rime also has comment alignment.

Did you mean horizontal mode as linear mode? The code checks if now it is vertical mode, only the vertical mode will be calculated, leaving the horizontal mode.

Also thank you for that I found the candidate list style config has change `style/horizontal` to `style/candidate_list_layout` at https://github.com/rime/squirrel/commit/88e085a6e4fc778a7208e193c86f04d3e61c3b48, I should follow the new config.

**Comment by LEOYoon-Tsaw** [comment]
I also suggest making it configurable, I don’t feel I’m going to use it, I don’t want to be forced

**Comment by LEOYoon-Tsaw** [comment]
Actually users may add a tab to comment to achieve the same results. Perhaps there’s no need to change the code at all.

**Comment by LEOYoon-Tsaw** [comment]
This can be closed, as new candidate_format explicitly let user to choose the character between candidate and comment. If the user wish so, they can use `[candidate]\u09[comment]`

**Pull request closed without merging**
