### PR TITLE
chore(sparkle.framework): bump Sparkle to v1.24.0

### PR DESCRIPTION
**Pull request by kuoruan**
* New sparkle version compatible with both Intel and Apple Silicon (arm64/M1) Macs
  https://github.com/sparkle-project/Sparkle/releases/tag/1.24.0

 Framework files are copy from Sparkle-1.24.0.tar.xz

See #464

### CODE REVIEW

**Comment by kuoruan** [comment]
When revert commit: https://github.com/rime/squirrel/commit/51f62cf7e52d779f8721f2ffcf5fc2b6720155c3 and rebuild,

An error reported:

```
ld: warning: ignoring file /Users/kuoruan/squirrel/lib/librime.1.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64
Undefined symbols for architecture arm64:
  "_rime_get_api", referenced from:
      -[SquirrelConfig openBaseConfig] in SquirrelConfig.o
      -[SquirrelConfig openWithSchemaId:baseConfig:] in SquirrelConfig.o
      -[SquirrelConfig close] in SquirrelConfig.o
      -[SquirrelConfig hasSection:] in SquirrelConfig.o
      -[SquirrelConfig getOptionalBool:] in SquirrelConfig.o
      -[SquirrelConfig getOptionalInt:] in SquirrelConfig.o
      -[SquirrelConfig getOptionalDouble:] in SquirrelConfig.o
      ...
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

So there should be some changes to librime build files.

**Comment by lotem** [comment]
Thanks for the help. 

librime has also to be a universal binary even if only one architecture is run. I've done the universal build, and planning a release after fixing a few other issues with plugins.

FYI: I'm also looking into the branch
https://github.com/sparkle-project/Sparkle/releases/tag/1.24.0-spm which added a fix for using Xcode's builtin SwiftPackageManager to add Sparkle to the project as a dependency. Haven't done my experiment but looks promising since there is no need to check in the framework files into our repo; only need to configure the Xcode project. I can try it after this update.

**Comment by lotem** [comment]
One more TODO: check if the new Sparkle framework requires an update to the signing/release script and appcast.xml template.

**Comment by kuoruan** [comment]
Update to use `Swift Package Manager`

Xcode 11 and later is required

**Review by lotem — APPROVED** [review]

**Comment by lotem** [comment]
> One more TODO: check if the new Sparkle framework requires an update to the signing/release script and appcast.xml template.

tested: the existing appcast works after updating to new Sparkle framework.
Sparkle doc says the old signing algorithm is still supported for old apps.
therefore it is not required to finish the transition to new signing method immediately.

**Pull request closed without merging**
