### PR TITLE
chore(README.md): fix link to homepage

### PR DESCRIPTION
**Pull request by l2dy**
Following c372ff41d47facf86defbac25723da562efb73a0.

### CODE REVIEW

**Comment by lotem** [comment]
thanks for the pull request.

I'd like to keep `http:` in user visible urls for now, as long as nothing is broken.

a few considerations:
1) the link is everywhere before switching to https, changing all links requires a greater effort;
2) I want readers pay no attention to parts they don't have to remember, and focus on the host "rime.im"; making the change would gain nothing, only distract readers.

on the other hand, https://github.com/rime/squirrel/commit/c372ff41d47facf86defbac25723da562efb73a0 changed a url which is not inlined; it was necessary as the .md file is also converted to a html page on rime.im, where the link was broken without the protocol part - the site generator wrongly converted it to a relative path `/rime.im/`.

**Comment by l2dy** [comment]
> 2. I want readers pay no attention to parts they don't have to remember, and focus on the host "rime.im"; making the change would gain nothing, only distract readers.

I'd argue that https protects users from MITM attacks. For example, if a malicious ISP using [sslstrip](https://github.com/moxie0/sslstrip) replaced the binary download link (Squirrel-0.10.0.zip), they could inject malicious code and compromise the users' devices. The Squirrel pkg is not signed, and I can't find any checksum or signatures published for it, so I believe the readers are vulnerable to this attack.

**Comment by l2dy** [comment]
> 1. the link is everywhere before switching to https, changing all links requires a greater effort;

Indeed, but as stated above it does benefit the readers. And I think we shouldn't reject small improvements because of the total amount of effort required, the work can be done bit by bit and the community can help.

I can open another pull request if you request it, it looks like this pull request can't be reopened now.

**Comment by lotem** [comment]
No worries. HTTPS is enforced on the site rime.im. Users won't be able to visit the site without secure connection following the http: link. That's why I don't think this should have priority.
When I mentioned "everywhere", it wasn't just this codebase. There are a good many of them on the internet, for example this one: https://github.com/rime/rime-middle-chinese/blob/master/README.md
It also involve the question how I should introduce the project in chat with people, on social media etc. I have to be consistent and the current strategy works well.

**Comment by l2dy** [comment]
> No worries. HTTPS is enforced on the site rime.im. Users won't be able to visit the site without secure connection following the http: link. That's why I don't think this should have priority.

How is it enforced? sslstrip can watch for HTTPS *links* and *redirects*, then map those links into either look-alike HTTP links or homograph-similar HTTPS links[1]. So if a reader is following the http: link, and a malicious actor (ISP or another device doing ARP spoofing) runs sslstrip in their network, HTTPS is not enforced for them. The attacker can then serve malicious packages and compromise the reader's device.

[1] https://moxie.org/software/sslstrip/

**Comment by lotem** [comment]
Wow. That indeed sound scary to me.
Thanks for the information. I'll look into that.

**Comment by l2dy** [comment]
@lotem Do you think we can gradually upgrade all rime.im links to `https://`?

**Comment by lotem** [comment]
@l2dy Thanks again for raising the concern.
I just replaced (almost) all `http://` links in all Rime projects using a script.
However in a few occasions `https://` links do not work with third-party software.

**Comment by l2dy** [comment]
Please also replace the link on https://github.com/rime.

**Comment by lotem** [comment]
> Please also replace the link on https://github.com/rime.

Done.

**Pull request closed without merging**
