### PR TITLE
Build Sparkle from source

### PR DESCRIPTION
**Pull request by LEOYoon-Tsaw**
Building Sparkle from source is more flexible in choosing between different architectures to support.

### CODE REVIEW

**Comment by lotem** [comment]
I lean towards using an official binary release.
Pros:
  - reliable source;
  - faster (CI) build;
  - requires no extra attention of source code users; [ci failure](https://travis-ci.org/github/rime/squirrel/builds/756892276) is a sign;
 
Cons:
  - updating the framework creates a large diff; but we won't update unless there is a must.

The flexibility to build for other architectures is not a big issue. A universal build is sufficient.

**Comment by LEOYoon-Tsaw** [comment]
Well, it's an option, I don't have particular preference. But the reasons of building from source are:
1. The submodule can be set to specific branch/commit, reliability is not an issue
2. Building Sparkle is fast, only takes less than 1 minute to build
2. The size difference in Universal and architecture specific Sparkle is roughly 2MB
3. All other parts of rime are in source code, having a binary in the project is inelegant

**Comment by LEOYoon-Tsaw** [comment]
Build passed, I forgot to `mkdir -p Frameworks` in makefile

**Comment by lotem** [comment]
> Well, it's an option, I don't have particular preference. But the reasons of building from source are:
> 
> 1. The submodule can be set to specific branch/commit, reliability is not an issue
> 2. Building Sparkle is fast, only takes less than 1 minute to build
> 3. The size difference in Universal and architecture specific Sparkle is roughly 2MB
> 4. All other parts of rime are in source code, having a binary in the project is inelegant
> 
> I actually like the previous experiment with SPM, but it just turns out SPM is not reliable enough, but submodule is reliable enough, and is equivalent in functionality.

Reasonable. Let me have a try.

**Comment by lotem** [comment]
I quickly gave up the try.
For me it takes forever to clone the submodule. Maybe it's because of the network. But that definitely hinders developers' velocity.
Compare the [PR build](https://travis-ci.org/github/rime/squirrel/builds/756911116) to [latest master build](https://travis-ci.org/github/rime/squirrel/builds/756859485), the time diff "4 min 22 sec" vs. "3 min 31 sec" is a significant increase.

**Comment by LEOYoon-Tsaw** [comment]
Sparkle source code is 12MB in size, it’s large, but not unacceptably large. Capnproto is 8.3MB, opens is 7.6MB, yaml is 6.6MB, all these third party reps are cloned with a combined size way larger than sparkle.

**Comment by lotem** [comment]
I'm sitting on the fence.
But now I need to skip this to move fast for a release.

**Comment by LEOYoon-Tsaw** [comment]
Of course, it's a minor pull, and doesn't affect user

**Comment by LEOYoon-Tsaw** [comment]
Replaced with #749

**Pull request closed without merging**
