### PR TITLE
adjust emoji font size to fix #501

### LINKED ISSUE #501: 最新的编译版本候选栏高度会随着是否有Emoji而变化
效果如录屏所示:
https://user-images.githubusercontent.com/5424240/106542099-1fc03500-653e-11eb-827c-b879c5bf43d8.mov

我是通过 https://dl.bintray.com/rime/squirrel/ 下载的编译版本,  
该问题从0.14.0比较新的某个版本引入,直到Squirrel-0.15.0+git8ed6ce5.zip仍能复现.  
而0.14.0正式版并没有该问题.

所使用设备:2018 MacBook ProPro, 2020 Mac Mini
所使用系统版本:11.1, 11.2
在以上设备及版本上皆能复现此效果.

### PR DESCRIPTION
**Pull request by LEOYoon-Tsaw**
fix #501

### CODE REVIEW

**Comment by lotem** [comment]
I don't like this change. User shouldn't have to take extra care of emojis. Why can't they just follow text font size?

**Comment by LEOYoon-Tsaw** [comment]
> I don't like this change. User shouldn't have to take extra care of emojis. Why can't they just follow text font size?

Emojis are taller than Hanzi or latin letters, the extra height will cause CoreStorage to render a line containing emoji higher than a line that not. Previously, before changing to CoreStorage, NSAttributedString renders with constant line height, converting to CoreStorage causes the line height to vary depending on whether an emoji enters.

The old way makes the vertical gap between 2 emoji lines smaller, but tho total line height is the same, it's not necessarily better, because lines with emojis will feel more squeezed, but is not noticeable in horizontal layout.

CoreStorage is really good at drawing hilighted strips, there's no reason to go back to NSAttributedString, but for those who really care about constant line height, they can use this option to achieve that.

**Comment by lotem** [comment]
I agree we should stick to CoreStorage. I looked carefully through the video in #501, the emoji size looks quite natural compared to text next to it; Apple probably mades emojis larger on intention.
Can we try making line height unaffected by emojis, caculated according to Chinese characters' size? Because when emojis appear in the video report, space above the emoji square also unnessessarily became larger than space below the emoji. That can be overcome by a maybe simpler solution by controlling line height without changing emoji font size.

**Comment by lotem** [comment]
> I agree we should stick to CoreStorage. I looked carefully through the video in #501, the emoji size looks quite natural compared to text next to it; Apple probably mades emojis larger on intention.
> Can we try making line height unaffected by emojis, caculated according to Chinese characters' size? Because when emojis appear in the video report, space above the emoji square also unnessessarily became larger than space below the emoji. That can be overcome by a maybe simpler solution by controlling line height without changing emoji font size.

Not sure if it is simpler. Please evaluate.
I remember that you measured single Chinese character's size during layout. Maybe we can determine line height based on that size, not the rendered size of the line.
That way square emojis still stay in the line, but some emojis like the toilet may use space above the line. Let's ignore the extreme case when border height and line spacing are all set to 0. Have a try to see if it renders okay in the default setup.

**Comment by LEOYoon-Tsaw** [comment]
Some test code
```Objective-C
//
//  main.m
//  test
//
//  Created by LEO Yoon-Tsaw on 2/2/21.
//

#import <Foundation/Foundation.h>
#import <Cocoa/Cocoa.h>

int main(int argc, const char * argv[]) {
    @autoreleasepool {
        // insert code here...
        NSString *str = @"Something🔥️";
        NSMutableParagraphStyle *paragraphStyle = [[NSParagraphStyle defaultParagraphStyle] mutableCopy];
       paragraphStyle.maximumLineHeight = 25;
        NSDictionary *attri = @{NSFontAttributeName: [NSFont fontWithName:@"SourceHanSans-Light" size:15],
                                NSParagraphStyleAttributeName: paragraphStyle,
                                NSBaselineOffsetAttributeName: @(0)};
        NSMutableAttributedString *str2 = [[NSMutableAttributedString alloc] initWithString:str attributes:attri];

        NSRect cjkRect = [str2 boundingRectWithSize:NSZeroSize options:0];
        NSLog(@"AttString: %f, %f", cjkRect.size.width, cjkRect.size.height);
        
        NSTextContainer *textContainer = [[NSTextContainer alloc] initWithSize:NSZeroSize];
        NSLayoutManager *layoutManager = [[NSLayoutManager alloc] init];
        [layoutManager addTextContainer:textContainer];
        NSTextStorage *text = [[NSTextStorage alloc] init];
        [text addLayoutManager:layoutManager];
        [text setAttributedString:str2];
        
        text.layoutManagers[0].textContainers[0].containerSize = NSMakeSize(200, 0);
        NSRange glyphRange = [text.layoutManagers[0] glyphRangeForTextContainer:text.layoutManagers[0].textContainers[0]];
        NSRect rect = [text.layoutManagers[0] boundingRectForGlyphRange:glyphRange inTextContainer:text.layoutManagers[0].textContainers[0]];
        NSLog(@"CoreStorage: %f, %f", rect.size.width, rect.size.height);

        NSParagraphStyle *paraStyle = [text attribute:NSParagraphStyleAttributeName atIndex:0 effectiveRange:NULL];
        NSLog(@"%f", paraStyle.maximumLineHeight);
    }
    return 0;
}
```

**Comment by LEOYoon-Tsaw** [comment]
One possible alternative is to specify minimum line height with the emoji height. The side effect is a higher lower bound of line height

**Comment by lotem** [comment]
Thanks for doing the experiment. So specify a desired line height doesn't work. What I wanted to achieve was to have a controlled line height in the logical sense, maybe realized by bottom- or base- aligning the text to its usual position (as if without emojis), however high the line is actually rendered. Is that possible?

**Comment by LEOYoon-Tsaw** [comment]
Offset is just off set, won't change line height. You will observe same behavior in Pages, Xcode, but in Messages, built-in input, emoji doesn't change line height, so this behavior does exist in macOS, but maybe avoidable, just I don't know. Before someone figures out how, just give them this option to change emoji size, all they want is just a fixed line height.

**Comment by lotem** [comment]
​No need to hurry.
I don't want to introduce a new configuration item because of the need for a quick fix. Once introduced, we have to support the option for a considerable lengths of time. So I wish that we arrive at a thought-out solution.
If you think speeding more time on the issue is unworthy, or really want to push for a quick launch, then I think we may figure out a safe factor to scale down emojis, and apply the fix automatically, then most users stay unaffected.

**Comment by LEOYoon-Tsaw** [comment]
image
Automatic smaller emoji, not so bad

**Pull request merged**
